apiVersion: v1
kind: Service
metadata:
  name: product-backend
  labels:
    app: product-backend
spec:
  type: ClusterIP
  selector:
    app: product-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000

